[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM19
monitor_speed = 921600

lib_deps =
    lvgl/lvgl@^8.3.11 ; Use strict version for stability
    bodmer/TFT_eSPI@^2.5.43

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_CONF_SUPPRESS_DEFINE_CHECK
    ; -D LV_USE_DRAW_SW_ASM=0 ; Allow ASM if available
    -Ofast
    -I include
    
    ; PSRAM Config for N16R8
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    
    ; ESP32-S3 Pinout & Display Config
    -D USER_SETUP_LOADED=1
    -D ILI9488_DRIVER=1
    -D USE_FSPI_PORT=1
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=9
    -D TFT_RST=46
    -D TFT_BL=3
    -D TOUCH_CS=-1
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
    
    ; Color Order (Fixes Blue/Red swap usually)
    -D TFT_RGB_ORDER=TFT_BGR
    ; -D TFT_INVERSION_ON ; Try if black is white
    
    ; Font Loading
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=1
    
    ; Hardware Helpers
    -D TOUCH_SDA=8
    -D TOUCH_SCL=18
    -D TOUCH_INT=17
    -D TOUCH_RST=16
    -D ROT_CLK=4
    -D ROT_DT=5
    -D ROT_SW=6
